name: Approve Pull Request made by Repo Owner
author: juliangruber
description: 'A GitHub Action for approving pull requests made by the repo owner'
branding:
  icon: 'git-pull-request'
  color: green
inputs:
  github-token:
    description: 'GitHub Token'
    required: true  
runs:
  using: 'node20'
  main: 'dist/index.js'
